## PaperTrail example Daemonset
# Uncomment sections below to allow audit logs to go to a separate host

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:papertrail
        ports:
        - containerPort: 24231
          name: metrics
        env:
          - name: FLUENT_PAPERTRAIL_HOST
            value: "logsX.papertrailapp.com"
          - name: FLUENT_PAPERTRAIL_PORT
            value: "XXXXX"
#          - name: FLUENT_PAPERTRAIL_AUDIT_HOST
#            value: "<PAPERTRAIL_AUDIT_HOST>"
#          - name: FLUENT_PAPERTRAIL_AUDIT_PORT
#            value: "<PAPERTRAIL_AUDIT_PORT>"
          - name: FLUENT_HOSTNAME
            value: "MYCLUSTER"
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
#---
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: fluentd-config
#  namespace: kube-system
#  labels:
#    k8s-app: fluentd-logging
#    version: v1
#    kubernetes.io/cluster-service: "true"
#data:
#  fluent.conf: |-
#    @include kubernetes.conf
#
#    # Capture audit logs
#    <match kube-apiserver-audit>
#      type papertrail
#
#      papertrail_host "#{ENV['FLUENT_PAPERTRAIL_AUDIT_HOST']}"
#      papertrail_port "#{ENV['FLUENT_PAPERTRAIL_AUDIT_PORT']}"
#    </match>
#
#    # Capture all unmatched tags
#    <match **>
#      type papertrail
#
#      papertrail_host "#{ENV['FLUENT_PAPERTRAIL_HOST']}"
#      papertrail_port "#{ENV['FLUENT_PAPERTRAIL_PORT']}"
#    </match>