apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:secureforward
        env:
          - name:  FLUENT_SECURE_FORWARD_SHARED_KEY
            value: "YOURSECRET"
          - name:  FLUENT_SECURE_FORWARD_CERT_PATH
            value: "/fluent/tls.cert"
          - name:  FLUENT_SECURE_FORWARD_REMOTE_HOST
            value: "YOU_REMOTE_HOST"
          # - name:  FLUENT_SECURE_FORWARD_PORT
          #   value: "24284" # Default port
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluentTLS
          mountPath: /fluent/tls.cert
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluentTLS
        configMap:
          name: fluentTLS.cert