---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd
roleRef:
  kind: ClusterRole
  name: fluentd
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: fluentd
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-azureblob
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
    version: v1
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-logging
      version: v1
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd-azureblob
        image: fluent/fluentd-kubernetes-daemonset:v1-debian-azureservicebus
        imagePullPolicy: Always
        env:
          - name: AZURESERVICEBUS_NAMESPACE
            value: "mynamespace"
          - name:  AZURESERVICEBUS_QUEUENAME
            value: "myqueuename"
          - name:  AZURESERIVCEBUS_ACCESSKEYNAME
            value: "myaccesskeyname"
          - name:  AZURESERIVCEBUS_ACCESSKEYVALUEFILE
            value: "/etc/password/queuePassword"
          - name:  AZURESERIVCEBUS_TIMETOLIVE
            value: "60"
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        # When actual pod logs in /var/lib/docker/containers, the following lines should be used.
        # - name: dockercontainerlogdirectory
        #   mountPath: /var/lib/docker/containers
        #   readOnly: true
        # When actual pod logs in /var/log/pods, the following lines should be used.
        - name: dockercontainerlogdirectory
          mountPath: /var/log/pods
          readOnly: true
        - mountPath: "/etc/password"
          name: azure-serivcebus-access-key-value-file
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      # When actual pod logs in /var/lib/docker/containers, the following lines should be used.
      # - name: dockercontainerlogdirectory
      #   hostPath:
      #     path: /var/lib/docker/containers
      # When actual pod logs in /var/log/pods, the following lines should be used.
      - name: dockercontainerlogdirectory
        hostPath:
          path: /var/log/pods
      - name: azure-serivcebus-access-key-value-file
        secret:
          secretName: azure-serivcebus-access-key-value-file
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-serivcebus-access-key-value-file
  namespace: kube-system
data:
  # Remember to change the password
  queuePassword: "MYQUEUEPASSWORD"
