apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd-loomsystems
  namespace: kube-system
  labels:
    k8s-app: fluentd-loomsystems
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: fluentd-loomsystems
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: loomsystems/fluentd-kubernetes-loomsystems:v0.12.43-loomsystems
        imagePullPolicy: Always
        env:
        - name:  LOOM_RECIEVER_HOST
          value: "{{RECEIVER HOST}}"
        - name:  LOOM_RECIEVER_SSL_PORT
          value: "{{SSL PORT}}"
        - name:  LOOM_USE_SSL
          value: "true"
          #use when LOOM_USE_SSL is false
        - name:  LOOM_RECIEVER_PORT
          value: "{{RECEIVER PORT}}"
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
    serviceAccountName: build-robot