---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-logentries
  namespace: kube-system
data:
  tokens.yaml: |
    # use the same token for all logs
    "":
       app: TOKEN # set your token here

---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
  labels:
    k8s-app: fluentd
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: fluentd
        kubernetes.io/cluster-service: "true"
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1.2-debian-logentries
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: logentries-config
          mountPath: /etc/logentries
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        env:
        - name: FLUENTD_SYSTEMD_CONF
          value: "disable"
        #- name: FLUENT_LOGENTRIES_TAG_ACCESS_LOG
        #  value: "stdout"
        #- name: FLUENT_LOGENTRIES_TAG_ERROR_LOG
        #  value: "stderr"
        #- name: FLUENT_LOGENTRIES_USE_SSL
        #  value: "true"
        - name: FLUENT_LOGENTRIES_USE_JSON
          value: "true"
        - name: FLUENT_LOGENTRIES_PORT
          value: "443"
        #- name: FLUENT_LOGENTRIES_PROTOCOL
        #  value: "tcp"
        #- name: FLUENT_LOGENTRIES_CONFIG_PATH
        #  value: "/etc/logentries/tokens.yaml"
        #- name: FLUENT_LOGENTRIES_MAX_RETRIES
        #  value: "3"
        #- name: FLUENT_LOGENTRIES_TAG_ACCESS_LOG
        #  value: "logs-access"
        #- name: FLUENT_LOGENTRIES_TAG_ERROR_LOG
        #  value: "logs-error"
        #- name: FLUENT_LOGENTRIES_NO_SSL_HOST
        #  value: "REGION.data.logs.insight.rapid7.com"
        #- name: FLUENT_LOGENTRIES_SSL_HOST
        #  value: "REGION.data.logs.insight.rapid7.com"
      terminationGracePeriodSeconds: 30
      volumes:
      - name: logentries-config
        configMap:
          name: fluentd-logentries
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
